import type { Ritual } from './types'

export const RITUALS: Ritual[] = [
  {
    id: 'morning',
    category: 'morning',
    dialogueKey: 'morning',
    sprite: 'default',
    cooldownHours: 12,
    acceptLabel: "Let's go",
  },
  {
    id: 'medicine',
    category: 'medicine',
    dialogueKey: 'medicine',
    sprite: 'default',
    cooldownHours: 8,
    acceptLabel: "Let's Take Our Medicine",
  },
  {
    id: 'water',
    category: 'water',
    dialogueKey: 'water',
    sprite: 'drinking',
    cooldownHours: 2,
    acceptLabel: 'Drink',
    dismissLabel: 'later',
  },
  {
    id: 'lunch',
    category: 'lunch',
    dialogueKey: 'lunch',
    sprite: 'default',
    cooldownHours: 4,
    acceptLabel: "Let's eat",
  },
  {
    id: 'outdoors',
    category: 'outdoors',
    dialogueKey: 'outdoors',
    sprite: 'default',
    cooldownHours: 6,
    acceptLabel: "Let's go outside",
  },
  {
    id: 'walks',
    category: 'walks',
    dialogueKey: 'walks',
    sprite: 'default',
    cooldownHours: 6,
    acceptLabel: "Let's Walk",
    dismissLabel: 'Later',
  },
  {
    id: 'dinner',
    category: 'dinner',
    dialogueKey: 'dinner',
    sprite: 'default',
    cooldownHours: 4,
    acceptLabel: "Let's Eat",
  },
  {
    id: 'stretch',
    category: 'stretch',
    dialogueKey: 'stretch',
    sprite: 'stretch',
    cooldownHours: 4,
    acceptLabel: "Let's stretch",
  },
  {
    id: 'evening',
    category: 'evening',
    dialogueKey: 'evening',
    sprite: 'resting',
    cooldownHours: 6,
    acceptLabel: "Let's wind down",
  },
  {
    id: 'rest',
    category: 'rest',
    dialogueKey: 'rest',
    sprite: 'resting',
    cooldownHours: 4,
    acceptLabel: "Let's Rest",
  },
  {
    id: 'bedtime',
    category: 'bedtime',
    dialogueKey: 'bedtime',
    sprite: 'sleeping',
    cooldownHours: 12,
    acceptLabel: 'Good Night',
  },
  {
    id: 'cuddles',
    category: 'cuddles',
    dialogueKey: 'cuddles',
    sprite: 'default',
    cooldownHours: 3,
  },
  {
    id: 'random_affection',
    category: 'random_affection',
    dialogueKey: 'random_affection',
    sprite: 'default',
    cooldownHours: 2,
  },
  {
    id: 'encouragement',
    category: 'encouragement',
    dialogueKey: 'encouragement',
    sprite: 'default',
    cooldownHours: 4,
  },
  {
    id: 'random_nudge_1',
    category: 'play',
    dialogueKey: 'play',
    sprite: 'play',
    cooldownHours: 3,
    acceptLabel: 'Of course',
    dismissLabel: 'later',
  },
  {
    id: 'random_nudge_2',
    category: 'random_nudge_2',
    dialogueKey: 'random_nudge_2',
    sprite: 'ear_fix',
    cooldownHours: 3,
    acceptLabel: 'fix your ear',
    acceptVariant: 'purple',
    showDismiss: false,
  },
]

export function getRitualById(id: string): Ritual | undefined {
  return RITUALS.find((ritual) => ritual.id === id)
}
